# Generated by Django 6.1.1 on 2026-09-03 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('punch_in', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('working_hours', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-punch_in'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_attendance_per_day')],
            },
        ),
    ]
