# Generated by Django 6.1.1 on 2026-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punching', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
